[workspace]
members = ["macros"]

[package]
name = "woab"
version = "0.1.0"
description = "Bridge between GTK and Actix to create actor-based GUIs"
authors = ["IdanArye <idanarye@gmail.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/idanarye/woab"
documentation = "https://idanarye.github.io/woab/"
readme = "../README.md"
keywords = ["gtk", "gui", "actix", "actor"]
categories = ["gui"]

[dependencies]
gtk = "^0.9"
actix = "^0.9"
tokio = "^0.2"
glib = "^0.10"
woab-macros = { path = "macros" }
quick-xml = "0.18.1"
thiserror = "1.0.20"

[dev-dependencies]
futures-util = "0.3.5"
gtk-test = "0.6.1"
anyhow = "1.0.32"
