name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages for gtk-test
      run: |-
        sudo apt-get update
        sudo apt-get install xvfb
        sudo apt-get install libgtk-3-dev
        sudo apt-get install libxdo-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: xvfb-run cargo test --verbose -- --nocapture --test-threads 1
    - name: Build docs
      if: ${{ !(github.github.head_ref) }}
      env:
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        cargo doc --verbose &&
        echo "<meta http-equiv=refresh content=0;url=woab/index.html>" > target/doc/index.html &&
        pip install ghp-import --user && export PATH=$HOME/.local/bin:$PATH &&
        ghp-import -n target/doc &&
        git push -fq https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git gh-pages
